"""add audit fields to resignation and clearance

Revision ID: 14156993bbdc
Revises: 80bef5c68b9d
Create Date: 2026-03-19 17:13:49.305492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14156993bbdc'
down_revision: Union[str, Sequence[str], None] = '80bef5c68b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clearance_records', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clearance_records', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clearance_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('clearance_records', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('clearance_records', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('clearance_records', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('resignations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('resignations', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('resignations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('resignations', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('resignations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('resignations', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resignations', 'deleted_by')
    op.drop_column('resignations', 'deleted_at')
    op.drop_column('resignations', 'updated_by')
    op.drop_column('resignations', 'updated_at')
    op.drop_column('resignations', 'created_by')
    op.drop_column('resignations', 'created_at')
    op.drop_column('clearance_records', 'deleted_by')
    op.drop_column('clearance_records', 'deleted_at')
    op.drop_column('clearance_records', 'updated_by')
    op.drop_column('clearance_records', 'updated_at')
    op.drop_column('clearance_records', 'created_by')
    op.drop_column('clearance_records', 'created_at')
    # ### end Alembic commands ###
