"""add audit fields to hiring_requests

Revision ID: 4f0c9811d6e6
Revises: d6941e8537ef
Create Date: 2026-03-19 16:10:31.330472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0c9811d6e6'
down_revision: Union[str, Sequence[str], None] = 'd6941e8537ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_requests', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('hiring_requests', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('hiring_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('hiring_requests_created_by_fkey'), 'hiring_requests', type_='foreignkey')
    op.create_foreign_key(None, 'hiring_requests', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'hiring_requests', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'hiring_requests', 'employees', ['updated_by'], ['id'])
    op.drop_column('job_postings', 'updated_at')
    op.drop_column('job_postings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.create_foreign_key(op.f('hiring_requests_created_by_fkey'), 'hiring_requests', 'employees', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('hiring_requests', 'deleted_at')
    op.drop_column('hiring_requests', 'deleted_by')
    op.drop_column('hiring_requests', 'updated_by')
    # ### end Alembic commands ###
