"""hiring model change

Revision ID: 6921a79586f5
Revises: 44b5e210b095
Create Date: 2026-03-13 00:22:59.886535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6921a79586f5'
down_revision: Union[str, Sequence[str], None] = '44b5e210b095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hiring_requests', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_requests', sa.Column('approval_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
