"""add audit fields to onboarding

Revision ID: 80bef5c68b9d
Revises: f8363ec21dd1
Create Date: 2026-03-19 17:06:14.433773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bef5c68b9d'
down_revision: Union[str, Sequence[str], None] = 'f8363ec21dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job_postings', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'job_postings', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'employees', ['updated_by'], ['id'])
    op.add_column('onboarding', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('onboarding', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('onboarding', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('onboarding', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('onboarding', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('onboarding', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding', 'deleted_by')
    op.drop_column('onboarding', 'deleted_at')
    op.drop_column('onboarding', 'updated_by')
    op.drop_column('onboarding', 'updated_at')
    op.drop_column('onboarding', 'created_by')
    op.drop_column('onboarding', 'created_at')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'deleted_at')
    op.drop_column('job_postings', 'deleted_by')
    op.drop_column('job_postings', 'updated_by')
    op.drop_column('job_postings', 'created_by')
    op.drop_column('job_postings', 'updated_at')
    # ### end Alembic commands ###
