"""fix role audit fields

Revision ID: 8bb935e32a43
Revises: 14156993bbdc
Create Date: 2026-03-19 17:25:14.959135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bb935e32a43'
down_revision: Union[str, Sequence[str], None] = '14156993bbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('roles', 'deleted_by')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'updated_by')
    # ### end Alembic commands ###
