"""simplify leave audit

Revision ID: dcc8decb9279
Revises: fbd7d5d139ff
Create Date: 2026-03-19 16:54:00.378349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcc8decb9279'
down_revision: Union[str, Sequence[str], None] = 'fbd7d5d139ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_employee_leave'), 'leave_balances', type_='unique')
    op.drop_constraint(op.f('leave_balances_created_by_fkey'), 'leave_balances', type_='foreignkey')
    op.drop_constraint(op.f('leave_balances_deleted_by_fkey'), 'leave_balances', type_='foreignkey')
    op.drop_constraint(op.f('leave_balances_updated_by_fkey'), 'leave_balances', type_='foreignkey')
    op.drop_column('leave_balances', 'deleted_at')
    op.drop_column('leave_balances', 'deleted_by')
    op.drop_column('leave_balances', 'created_by')
    op.drop_column('leave_balances', 'updated_by')
    op.drop_column('leave_balances', 'created_at')
    op.drop_column('leave_balances', 'updated_at')
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('leave_requests_created_by_fkey'), 'leave_requests', type_='foreignkey')
    op.drop_constraint(op.f('leave_requests_updated_by_fkey'), 'leave_requests', type_='foreignkey')
    op.drop_constraint(op.f('leave_requests_deleted_by_fkey'), 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'deleted_at')
    op.drop_column('leave_requests', 'deleted_by')
    op.alter_column('leave_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('leave_types_created_by_fkey'), 'leave_types', type_='foreignkey')
    op.drop_constraint(op.f('leave_types_deleted_by_fkey'), 'leave_types', type_='foreignkey')
    op.drop_constraint(op.f('leave_types_updated_by_fkey'), 'leave_types', type_='foreignkey')
    op.drop_column('leave_types', 'updated_at')
    op.drop_column('leave_types', 'updated_by')
    op.drop_column('leave_types', 'deleted_at')
    op.drop_column('leave_types', 'deleted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_types', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leave_types', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_types', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leave_types_updated_by_fkey'), 'leave_types', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('leave_types_deleted_by_fkey'), 'leave_types', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(op.f('leave_types_created_by_fkey'), 'leave_types', 'employees', ['created_by'], ['id'])
    op.alter_column('leave_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('leave_requests', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leave_requests_deleted_by_fkey'), 'leave_requests', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(op.f('leave_requests_updated_by_fkey'), 'leave_requests', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('leave_requests_created_by_fkey'), 'leave_requests', 'employees', ['created_by'], ['id'])
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('leave_balances', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leave_balances', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('leave_balances', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_balances', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_balances', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_balances', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leave_balances_updated_by_fkey'), 'leave_balances', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('leave_balances_deleted_by_fkey'), 'leave_balances', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(op.f('leave_balances_created_by_fkey'), 'leave_balances', 'employees', ['created_by'], ['id'])
    op.create_unique_constraint(op.f('unique_employee_leave'), 'leave_balances', ['employee_id', 'leave_type_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
