"""simplify leave audit

Revision ID: f8363ec21dd1
Revises: dcc8decb9279
Create Date: 2026-03-19 16:58:35.107922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8363ec21dd1'
down_revision: Union[str, Sequence[str], None] = 'dcc8decb9279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('leave_balances', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leave_requests', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('leave_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leave_types', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('leave_types', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leave_types', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'deleted_by')
    op.drop_column('leave_types', 'deleted_at')
    op.drop_column('leave_types', 'updated_by')
    op.drop_column('leave_types', 'updated_at')
    op.drop_column('leave_requests', 'deleted_by')
    op.drop_column('leave_requests', 'deleted_at')
    op.drop_column('leave_balances', 'created_by')
    op.drop_column('leave_balances', 'created_at')
    # ### end Alembic commands ###
