"""add audit fields to leave

Revision ID: fbd7d5d139ff
Revises: aa0ae83dafa6
Create Date: 2026-03-19 16:49:36.553166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd7d5d139ff'
down_revision: Union[str, Sequence[str], None] = 'aa0ae83dafa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('leave_balances', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leave_balances', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('leave_balances', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('leave_balances', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leave_balances', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leave_balances', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'leave_balances', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'leave_balances', 'employees', ['created_by'], ['id'])
    op.add_column('leave_requests', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('leave_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leave_requests', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leave_requests', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'employees', ['updated_by'], ['id'])
    op.add_column('leave_types', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('leave_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leave_types', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('leave_types', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('leave_types', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leave_types', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leave_types', 'employees', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'leave_types', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'leave_types', 'employees', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_types', type_='foreignkey')
    op.drop_constraint(None, 'leave_types', type_='foreignkey')
    op.drop_constraint(None, 'leave_types', type_='foreignkey')
    op.drop_column('leave_types', 'deleted_by')
    op.drop_column('leave_types', 'deleted_at')
    op.drop_column('leave_types', 'updated_by')
    op.drop_column('leave_types', 'created_by')
    op.drop_column('leave_types', 'updated_at')
    op.drop_column('leave_types', 'created_at')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'deleted_by')
    op.drop_column('leave_requests', 'deleted_at')
    op.drop_column('leave_requests', 'updated_by')
    op.drop_column('leave_requests', 'created_by')
    op.drop_column('leave_requests', 'updated_at')
    op.drop_column('leave_requests', 'created_at')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_column('leave_balances', 'deleted_by')
    op.drop_column('leave_balances', 'deleted_at')
    op.drop_column('leave_balances', 'updated_by')
    op.drop_column('leave_balances', 'created_by')
    op.drop_column('leave_balances', 'updated_at')
    op.drop_column('leave_balances', 'created_at')
    # ### end Alembic commands ###
