"""update employee model improvements

Revision ID: 19148acc898d
Revises: bf7fb368fe6a
Create Date: 2026-03-03 01:57:15.821207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19148acc898d'
down_revision: Union[str, Sequence[str], None] = 'bf7fb368fe6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.drop_constraint(op.f('employees_role_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_role_id_fkey'), 'employees', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
