"""CREATED AND UPDATED AT MODIFICATION

Revision ID: 6302e26e143e
Revises: efda201c859d
Create Date: 2026-03-03 02:34:30.591493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6302e26e143e'
down_revision: Union[str, Sequence[str], None] = 'efda201c859d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
