"""add hiring and job posting unique constraints

Revision ID: 9b05068dd64b
Revises: bfc9bad0d4b4
Create Date: 2026-03-10 00:05:36.877015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b05068dd64b'
down_revision: Union[str, Sequence[str], None] = 'bfc9bad0d4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_active_hiring_request_per_role_department', 'hiring_requests', ['department_id', 'role_title', 'is_active'])
    op.create_unique_constraint('uq_active_job_posting_per_hiring_request', 'job_postings', ['hiring_request_id', 'is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_active_job_posting_per_hiring_request', 'job_postings', type_='unique')
    op.drop_constraint('uq_active_hiring_request_per_role_department', 'hiring_requests', type_='unique')
    # ### end Alembic commands ###
