"""hiring model change

Revision ID: a54d76c92cc8
Revises: 6921a79586f5
Create Date: 2026-03-13 01:39:23.630437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54d76c92cc8'
down_revision: Union[str, Sequence[str], None] = '6921a79586f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_requests', sa.Column('manager_approved', sa.Boolean(), nullable=True))
    op.add_column('hiring_requests', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('hiring_requests', sa.Column('manager_approved_at', sa.DateTime(), nullable=True))
    op.add_column('hiring_requests', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hiring_requests', 'employees', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hiring_requests', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.drop_column('hiring_requests', 'created_by')
    op.drop_column('hiring_requests', 'manager_approved_at')
    op.drop_column('hiring_requests', 'manager_id')
    op.drop_column('hiring_requests', 'manager_approved')
    # ### end Alembic commands ###
