"""added expiry in auth token

Revision ID: b122db5fd77f
Revises: 
Create Date: 2026-03-12 20:55:03.037623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b122db5fd77f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.alter_column('auth_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth_tokens', 'expires_at')
    # ### end Alembic commands ###
