"""changes to employee

Revision ID: bf7fb368fe6a
Revises: 7b64300fb493
Create Date: 2026-03-03 01:43:00.013705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7fb368fe6a'
down_revision: Union[str, Sequence[str], None] = '7b64300fb493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_role_id'), 'employees', ['role_id'], unique=False)
    op.drop_constraint(op.f('employees_manager_id_fkey'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('employees_department_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_department_id_fkey'), 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('employees_manager_id_fkey'), 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_employees_role_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###
