"""training uniqueness constraint

Revision ID: bfc9bad0d4b4
Revises: e066c6f98761
Create Date: 2026-03-09 23:45:22.081595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc9bad0d4b4'
down_revision: Union[str, Sequence[str], None] = 'e066c6f98761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_training', 'training_records', ['employee_id', 'training_title', 'training_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_employee_training', 'training_records', type_='unique')
    # ### end Alembic commands ###
