"""update hiring and job posting models

Revision ID: efda201c859d
Revises: 5f55b3f7b31c
Create Date: 2026-03-03 02:12:13.113935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efda201c859d'
down_revision: Union[str, Sequence[str], None] = '5f55b3f7b31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'hiring_requests',
    sa.Column(
        'is_active',
        sa.Boolean(),
        nullable=False,
        server_default=sa.true()
    )
)

# Optional but cleaner (removes default after creation)
    op.alter_column('hiring_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('hiring_requests', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    
    op.add_column('hiring_requests', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='TRUE'))
    op.add_column('hiring_requests', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('hiring_requests', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), onupdate=sa.text('now()')))
    
    op.add_column('job_postings', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='TRUE'))
    op.add_column('job_postings', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('job_postings', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), onupdate=sa.text('now()')))


    op.create_index(op.f('ix_hiring_requests_department_id'), 'hiring_requests', ['department_id'], unique=False)
    op.create_index(op.f('ix_hiring_requests_id'), 'hiring_requests', ['id'], unique=False)
    op.drop_constraint(op.f('hiring_requests_department_id_fkey'), 'hiring_requests', type_='foreignkey')
    op.create_foreign_key(None, 'hiring_requests', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
 
    op.alter_column('job_postings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_index(op.f('ix_job_postings_hiring_request_id'), 'job_postings', ['hiring_request_id'], unique=False)
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.drop_constraint(op.f('job_postings_hiring_request_id_fkey'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'hiring_requests', ['hiring_request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_hiring_request_id_fkey'), 'job_postings', 'hiring_requests', ['hiring_request_id'], ['id'])
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_hiring_request_id'), table_name='job_postings')
    op.alter_column('job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('job_postings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('job_postings', 'updated_at')
    op.drop_column('job_postings', 'is_active')
    op.drop_constraint(None, 'hiring_requests', type_='foreignkey')
    op.create_foreign_key(op.f('hiring_requests_department_id_fkey'), 'hiring_requests', 'departments', ['department_id'], ['id'])
    op.drop_index(op.f('ix_hiring_requests_id'), table_name='hiring_requests')
    op.drop_index(op.f('ix_hiring_requests_department_id'), table_name='hiring_requests')
    op.alter_column('hiring_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hiring_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hiring_requests', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('hiring_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('hiring_requests', 'is_active')
    # ### end Alembic commands ###
